// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace PipeLines.Model.PipeItemModels
{
    class HorizontalPipe:PipeItem
    {
        public HorizontalPipe(int posX, int posY):base(posX,posY)
        {
            this.uriSource = new Uri("Assets/horizontal.png", UriKind.Relative);
            this.waterBackgroundSource = new Uri("Assets/horizontal_water.png", UriKind.Relative);
        }
        

        public override int[] possibleDirectionByPipeType(int x, int y)
        {
            int[] nextXY;

            if (this.Posx - 1 == x && this.PosY == y)
            {
                this.AnimationStartPoint = new Point(0, 0);
                this.AnimationEndPoint = new Point(1, 0);
                return (nextXY = new int[] { this.posX + 1, this.PosY });
            }               
            else if (this.Posx + 1 == x && this.PosY == y)
            {
                this.AnimationStartPoint = new Point(1, 0);
                this.AnimationEndPoint = new Point(0, 0);
                return (nextXY = new int[] { this.posX - 1, this.PosY });
            }                
            else return null;
        }
    }
}
