// <auto-generated />
using PipeLines.Model;
using PipeLines.Model.PipeItemModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Xml;

namespace PipeLines
{
    /// <summary>
    /// Source for the MainWindow
    /// </summary>
    public partial class MainWindow : Window
    {
        Page[] levelPages;
        int selectedPageIndex;
        public MainWindow()
        {
            InitializeComponent();

            levelPages = new Page[] { new Page1(), new Page2(), new Page3() };
            selectedPageIndex = 0;
            levels.Content = levelPages[selectedPageIndex];
            buttonLeft.Visibility = Visibility.Hidden;
        }
        /// <summary>
        /// Changing pages inside the frame
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Click_Left(object sender, RoutedEventArgs e)
        {
            if(selectedPageIndex>0)
            {
                levels.Content = levelPages[--selectedPageIndex];
                buttonRight.Visibility = Visibility.Visible;

                if(selectedPageIndex==0)
                    buttonLeft.Visibility = Visibility.Hidden;
            }
            
        }
        /// <summary>
        /// Changing pages inside the frame
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Click_Right(object sender, RoutedEventArgs e)
        {
            if (selectedPageIndex < 2)
            {
                levels.Content = levelPages[++selectedPageIndex];
                buttonLeft.Visibility = Visibility.Visible;

                if (selectedPageIndex == 2)
                    buttonRight.Visibility = Visibility.Hidden;
            }
        }
    }
}
