// <auto-generated />
using PipeLines.Model;
using PipeLines.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace PipeLines
{
    /// <summary>
    /// This page contains 3 buttons, to start the easy maps.
    /// </summary>
    public partial class Page1 : Page
    {
        GameWindowViewModel gwvm;
        public Page1()
        {
            InitializeComponent();
            gwvm = new GameWindowViewModel();
            gwvm.Diff = "EASY";
        }

        private void click1(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_1, gwvm);
            gameWindow.Show();
        }

        private void click2(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_2, gwvm);
            gameWindow.Show();
        }

        private void click3(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_3, gwvm);
            gameWindow.Show();
        }
    }
}
