// <auto-generated />
using PipeLines.Model;
using PipeLines.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace PipeLines
{
    /// <summary>
    /// This page contains 3 buttons, to start the hard maps.
    /// </summary>
    public partial class Page3 : Page
    {
        GameWindowViewModel gwvm;
        public Page3()
        {
            InitializeComponent();
            gwvm = new GameWindowViewModel();
            gwvm.Diff = "HARD";
        }

        private void click7(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_7, gwvm);
            gameWindow.Show();
        }

        private void click8(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_8, gwvm);
            gameWindow.Show();
        }

        private void click9(object sender, RoutedEventArgs e)
        {
            GameWindow gameWindow = new GameWindow(LevelNumber.lvl_9, gwvm);
            gameWindow.Show();
        }
    }
}
