// <auto-generated />
using PipeLines.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PipeLines.ViewModel
{
    /// <summary>
    /// GameWindowViewModel contains basic information, which is diplayed on UI elements in the gameWindow
    /// </summary>
    public class GameWindowViewModel:Bindable
    {
        private int moveCount;

        public int MoveCount
        {
            get { return moveCount; }
            set { moveCount = value; OnPropertyChanged("movecount"); }
        }

        private string diff;

        public string Diff
        {
            get { return diff; }
            set { diff = value; OnPropertyChanged("difficulty"); }
        }

        public GameWindowViewModel()
        {
            moveCount = 0;
        }
    }
}
